package sm83

// Instruction names provide stable mnemonic keys for lookup and tooling.
const (
	AdcName  = "adc"
	AddName  = "add"
	AndName  = "and"
	BitName  = "bit"
	CallName = "call"
	CcfName  = "ccf"
	CpName   = "cp"
	CplName  = "cpl"
	DaaName  = "daa"
	DecName  = "dec"
	DiName   = "di"
	EiName   = "ei"
	HaltName = "halt"
	IncName  = "inc"
	JpName   = "jp"
	JrName   = "jr"
	LdName   = "ld"
	LdhName  = "ldh"
	NopName  = "nop"
	OrName   = "or"
	PopName  = "pop"
	PushName = "push"
	ResName  = "res"
	RetName  = "ret"
	RetiName = "reti"
	RlName   = "rl"
	RlaName  = "rla"
	RlcName  = "rlc"
	RlcaName = "rlca"
	RrName   = "rr"
	RraName  = "rra"
	RrcName  = "rrc"
	RrcaName = "rrca"
	RstName  = "rst"
	SbcName  = "sbc"
	ScfName  = "scf"
	SetName  = "set"
	SlaName  = "sla"
	SraName  = "sra"
	SrlName  = "srl"
	StopName = "stop"
	SubName  = "sub"
	SwapName = "swap"
	XorName  = "xor"
)
