package sm83

// CBOpcodes maps CB-prefixed opcodes to instruction information.
// All 256 CB-prefixed opcodes are valid on the SM83.
// Timing is in M-cycles (machine cycles).
var CBOpcodes = [256]Opcode{
	// 0x00-0x07: RLC r
	0x00: {Instruction: CBRlc, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RLC B
	0x01: {Instruction: CBRlc, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RLC C
	0x02: {Instruction: CBRlc, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RLC D
	0x03: {Instruction: CBRlc, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RLC E
	0x04: {Instruction: CBRlc, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RLC H
	0x05: {Instruction: CBRlc, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RLC L
	0x06: {Instruction: CBRlc, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // RLC (HL)
	0x07: {Instruction: CBRlc, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RLC A
	// 0x08-0x0F: RRC r
	0x08: {Instruction: CBRrc, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RRC B
	0x09: {Instruction: CBRrc, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RRC C
	0x0A: {Instruction: CBRrc, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RRC D
	0x0B: {Instruction: CBRrc, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RRC E
	0x0C: {Instruction: CBRrc, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RRC H
	0x0D: {Instruction: CBRrc, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RRC L
	0x0E: {Instruction: CBRrc, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // RRC (HL)
	0x0F: {Instruction: CBRrc, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RRC A
	// 0x10-0x17: RL r
	0x10: {Instruction: CBRl, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RL B
	0x11: {Instruction: CBRl, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RL C
	0x12: {Instruction: CBRl, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RL D
	0x13: {Instruction: CBRl, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RL E
	0x14: {Instruction: CBRl, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RL H
	0x15: {Instruction: CBRl, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RL L
	0x16: {Instruction: CBRl, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // RL (HL)
	0x17: {Instruction: CBRl, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RL A
	// 0x18-0x1F: RR r
	0x18: {Instruction: CBRr, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RR B
	0x19: {Instruction: CBRr, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RR C
	0x1A: {Instruction: CBRr, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RR D
	0x1B: {Instruction: CBRr, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RR E
	0x1C: {Instruction: CBRr, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RR H
	0x1D: {Instruction: CBRr, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RR L
	0x1E: {Instruction: CBRr, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // RR (HL)
	0x1F: {Instruction: CBRr, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RR A
	// 0x20-0x27: SLA r
	0x20: {Instruction: CBSla, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SLA B
	0x21: {Instruction: CBSla, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SLA C
	0x22: {Instruction: CBSla, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SLA D
	0x23: {Instruction: CBSla, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SLA E
	0x24: {Instruction: CBSla, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SLA H
	0x25: {Instruction: CBSla, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SLA L
	0x26: {Instruction: CBSla, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // SLA (HL)
	0x27: {Instruction: CBSla, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SLA A
	// 0x28-0x2F: SRA r
	0x28: {Instruction: CBSra, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SRA B
	0x29: {Instruction: CBSra, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SRA C
	0x2A: {Instruction: CBSra, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SRA D
	0x2B: {Instruction: CBSra, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SRA E
	0x2C: {Instruction: CBSra, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SRA H
	0x2D: {Instruction: CBSra, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SRA L
	0x2E: {Instruction: CBSra, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // SRA (HL)
	0x2F: {Instruction: CBSra, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SRA A
	// 0x30-0x37: SWAP r (SM83-unique, replaces Z80's SLL)
	0x30: {Instruction: CBSwap, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SWAP B
	0x31: {Instruction: CBSwap, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SWAP C
	0x32: {Instruction: CBSwap, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SWAP D
	0x33: {Instruction: CBSwap, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SWAP E
	0x34: {Instruction: CBSwap, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SWAP H
	0x35: {Instruction: CBSwap, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SWAP L
	0x36: {Instruction: CBSwap, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // SWAP (HL)
	0x37: {Instruction: CBSwap, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SWAP A
	// 0x38-0x3F: SRL r
	0x38: {Instruction: CBSrl, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SRL B
	0x39: {Instruction: CBSrl, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SRL C
	0x3A: {Instruction: CBSrl, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SRL D
	0x3B: {Instruction: CBSrl, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SRL E
	0x3C: {Instruction: CBSrl, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SRL H
	0x3D: {Instruction: CBSrl, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SRL L
	0x3E: {Instruction: CBSrl, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // SRL (HL)
	0x3F: {Instruction: CBSrl, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SRL A
	// 0x40-0x7F: BIT b,r
	0x40: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 0,B
	0x41: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 0,C
	0x42: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 0,D
	0x43: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 0,E
	0x44: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 0,H
	0x45: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 0,L
	0x46: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 3, Size: 2}, // BIT 0,(HL)
	0x47: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 0,A
	0x48: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 1,B
	0x49: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 1,C
	0x4A: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 1,D
	0x4B: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 1,E
	0x4C: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 1,H
	0x4D: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 1,L
	0x4E: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 3, Size: 2}, // BIT 1,(HL)
	0x4F: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 1,A
	0x50: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 2,B
	0x51: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 2,C
	0x52: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 2,D
	0x53: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 2,E
	0x54: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 2,H
	0x55: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 2,L
	0x56: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 3, Size: 2}, // BIT 2,(HL)
	0x57: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 2,A
	0x58: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 3,B
	0x59: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 3,C
	0x5A: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 3,D
	0x5B: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 3,E
	0x5C: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 3,H
	0x5D: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 3,L
	0x5E: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 3, Size: 2}, // BIT 3,(HL)
	0x5F: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 3,A
	0x60: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 4,B
	0x61: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 4,C
	0x62: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 4,D
	0x63: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 4,E
	0x64: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 4,H
	0x65: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 4,L
	0x66: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 3, Size: 2}, // BIT 4,(HL)
	0x67: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 4,A
	0x68: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 5,B
	0x69: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 5,C
	0x6A: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 5,D
	0x6B: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 5,E
	0x6C: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 5,H
	0x6D: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 5,L
	0x6E: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 3, Size: 2}, // BIT 5,(HL)
	0x6F: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 5,A
	0x70: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 6,B
	0x71: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 6,C
	0x72: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 6,D
	0x73: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 6,E
	0x74: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 6,H
	0x75: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 6,L
	0x76: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 3, Size: 2}, // BIT 6,(HL)
	0x77: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 6,A
	0x78: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 7,B
	0x79: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 7,C
	0x7A: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 7,D
	0x7B: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 7,E
	0x7C: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 7,H
	0x7D: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 7,L
	0x7E: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 3, Size: 2}, // BIT 7,(HL)
	0x7F: {Instruction: CBBit, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // BIT 7,A
	// 0x80-0xBF: RES b,r
	0x80: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 0,B
	0x81: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 0,C
	0x82: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 0,D
	0x83: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 0,E
	0x84: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 0,H
	0x85: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 0,L
	0x86: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // RES 0,(HL)
	0x87: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 0,A
	0x88: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 1,B
	0x89: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 1,C
	0x8A: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 1,D
	0x8B: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 1,E
	0x8C: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 1,H
	0x8D: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 1,L
	0x8E: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // RES 1,(HL)
	0x8F: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 1,A
	0x90: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 2,B
	0x91: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 2,C
	0x92: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 2,D
	0x93: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 2,E
	0x94: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 2,H
	0x95: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 2,L
	0x96: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // RES 2,(HL)
	0x97: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 2,A
	0x98: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 3,B
	0x99: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 3,C
	0x9A: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 3,D
	0x9B: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 3,E
	0x9C: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 3,H
	0x9D: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 3,L
	0x9E: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // RES 3,(HL)
	0x9F: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 3,A
	0xA0: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 4,B
	0xA1: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 4,C
	0xA2: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 4,D
	0xA3: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 4,E
	0xA4: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 4,H
	0xA5: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 4,L
	0xA6: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // RES 4,(HL)
	0xA7: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 4,A
	0xA8: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 5,B
	0xA9: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 5,C
	0xAA: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 5,D
	0xAB: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 5,E
	0xAC: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 5,H
	0xAD: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 5,L
	0xAE: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // RES 5,(HL)
	0xAF: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 5,A
	0xB0: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 6,B
	0xB1: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 6,C
	0xB2: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 6,D
	0xB3: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 6,E
	0xB4: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 6,H
	0xB5: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 6,L
	0xB6: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // RES 6,(HL)
	0xB7: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 6,A
	0xB8: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 7,B
	0xB9: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 7,C
	0xBA: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 7,D
	0xBB: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 7,E
	0xBC: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 7,H
	0xBD: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 7,L
	0xBE: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // RES 7,(HL)
	0xBF: {Instruction: CBRes, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // RES 7,A
	// 0xC0-0xFF: SET b,r
	0xC0: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 0,B
	0xC1: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 0,C
	0xC2: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 0,D
	0xC3: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 0,E
	0xC4: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 0,H
	0xC5: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 0,L
	0xC6: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // SET 0,(HL)
	0xC7: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 0,A
	0xC8: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 1,B
	0xC9: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 1,C
	0xCA: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 1,D
	0xCB: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 1,E
	0xCC: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 1,H
	0xCD: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 1,L
	0xCE: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // SET 1,(HL)
	0xCF: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 1,A
	0xD0: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 2,B
	0xD1: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 2,C
	0xD2: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 2,D
	0xD3: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 2,E
	0xD4: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 2,H
	0xD5: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 2,L
	0xD6: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // SET 2,(HL)
	0xD7: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 2,A
	0xD8: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 3,B
	0xD9: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 3,C
	0xDA: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 3,D
	0xDB: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 3,E
	0xDC: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 3,H
	0xDD: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 3,L
	0xDE: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // SET 3,(HL)
	0xDF: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 3,A
	0xE0: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 4,B
	0xE1: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 4,C
	0xE2: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 4,D
	0xE3: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 4,E
	0xE4: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 4,H
	0xE5: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 4,L
	0xE6: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // SET 4,(HL)
	0xE7: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 4,A
	0xE8: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 5,B
	0xE9: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 5,C
	0xEA: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 5,D
	0xEB: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 5,E
	0xEC: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 5,H
	0xED: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 5,L
	0xEE: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // SET 5,(HL)
	0xEF: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 5,A
	0xF0: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 6,B
	0xF1: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 6,C
	0xF2: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 6,D
	0xF3: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 6,E
	0xF4: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 6,H
	0xF5: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 6,L
	0xF6: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // SET 6,(HL)
	0xF7: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 6,A
	0xF8: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 7,B
	0xF9: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 7,C
	0xFA: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 7,D
	0xFB: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 7,E
	0xFC: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 7,H
	0xFD: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 7,L
	0xFE: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 4, Size: 2}, // SET 7,(HL)
	0xFF: {Instruction: CBSet, Addressing: RegisterAddressing, Timing: 2, Size: 2}, // SET 7,A
}
