package cpu68000

import "github.com/retroenv/retrogolib/set"

// BranchingInstructions contains all branching and jumping instructions.
var BranchingInstructions = set.NewFromSlice([]string{
	BccName,
	BRAName,
	BSRName,
	DBccName,
	JMPName,
	JSRName,
	RTEName,
	RTRName,
	RTSName,
})

// NotExecutingFollowingOpcodeInstructions contains all instructions that jump
// to a different address and do not return to execute the following opcode.
var NotExecutingFollowingOpcodeInstructions = set.NewFromSlice([]string{
	BRAName,
	JMPName,
	RTEName,
	RTSName,
	STOPName,
})

// MemoryReadInstructions contains all instructions that can read from memory
// through an operand or the stack. Instructions that only calculate an address
// (JMP, LEA, PEA) and exception-only reads are excluded.
var MemoryReadInstructions = set.NewFromSlice([]string{
	ABCDName,
	ADDName,
	ADDAName,
	ADDIName,
	ADDQName,
	ADDXName,
	ANDName,
	ANDIName,
	ASLName,
	ASRName,
	BCHGName,
	BCLRName,
	BSETName,
	BTSTName,
	CHKName,
	CLRName,
	CMPName,
	CMPAName,
	CMPIName,
	CMPMName,
	DIVSName,
	DIVUName,
	EORName,
	EORIName,
	LSLName,
	LSRName,
	MOVEName,
	MOVEAName,
	MOVEMName,
	MOVEPName,
	MULSName,
	MULUName,
	NBCDName,
	NEGName,
	NEGXName,
	NOTName,
	ORName,
	ORIName,
	ROLName,
	RORName,
	ROXLName,
	ROXRName,
	RTEName,
	RTRName,
	RTSName,
	SBCDName,
	SccName,
	SUBName,
	SUBAName,
	SUBIName,
	SUBQName,
	SUBXName,
	TASName,
	TSTName,
	UNLKName,
})

// MemoryWriteInstructions contains all instructions that can write to memory
// through an operand or the stack. Exception-only writes are excluded.
var MemoryWriteInstructions = set.NewFromSlice([]string{
	ABCDName,
	ADDName,
	ADDIName,
	ADDQName,
	ADDXName,
	ANDName,
	ANDIName,
	ASLName,
	ASRName,
	BCHGName,
	BCLRName,
	BSETName,
	BSRName,
	CLRName,
	EORName,
	EORIName,
	JSRName,
	LINKName,
	LSLName,
	LSRName,
	MOVEName,
	MOVEMName,
	MOVEPName,
	NBCDName,
	NEGName,
	NEGXName,
	NOTName,
	ORName,
	ORIName,
	PEAName,
	ROLName,
	RORName,
	ROXLName,
	ROXRName,
	SBCDName,
	SccName,
	SUBName,
	SUBIName,
	SUBQName,
	SUBXName,
	TASName,
})

// MemoryReadWriteInstructions contains all instructions that both read and write
// the same memory location during execution. The original 68000 also reads the
// destination of CLR and Scc before it writes.
var MemoryReadWriteInstructions = set.NewFromSlice([]string{
	ABCDName,
	ADDName,
	ADDIName,
	ADDQName,
	ADDXName,
	ANDName,
	ANDIName,
	ASLName,
	ASRName,
	BCHGName,
	BCLRName,
	BSETName,
	CLRName,
	EORName,
	EORIName,
	LSLName,
	LSRName,
	NBCDName,
	NEGName,
	NEGXName,
	NOTName,
	ORName,
	ORIName,
	ROLName,
	RORName,
	ROXLName,
	ROXRName,
	SBCDName,
	SccName,
	SUBName,
	SUBIName,
	SUBQName,
	SUBXName,
	TASName,
})
