package cpu6502

// Instructions maps instruction names to their definitions.
var Instructions = map[string]*Instruction{
	AdcName:   AdcInst,
	AlrName:   AlrInst,
	AncName:   AncInst,
	AndName:   AndInst,
	AneName:   AneInst,
	ArrName:   ArrInst,
	AslName:   AslInst,
	AxsName:   AxsInst,
	BccName:   BccInst,
	BcsName:   BcsInst,
	BeqName:   BeqInst,
	BitName:   BitInst,
	BmiName:   BmiInst,
	BneName:   BneInst,
	BplName:   BplInst,
	BraName:   BraInst,
	BrkName:   BrkInst,
	BvcName:   BvcInst,
	BvsName:   BvsInst,
	ClcName:   ClcInst,
	CldName:   CldInst,
	CliName:   CliInst,
	ClvName:   ClvInst,
	CmpName:   CmpInst,
	CpxName:   CpxInst,
	CpyName:   CpyInst,
	DcpName:   DcpInst,
	DecName:   DecInst,
	DexName:   DexInst,
	DeyName:   DeyInst,
	EorName:   EorInst,
	IncName:   IncInst,
	InxName:   InxInst,
	InyName:   InyInst,
	IscName:   IscInst,
	JmpName:   JmpInst,
	JsrName:   JsrInst,
	KilName:   KilInst,
	LasName:   LasInst,
	LaxName:   LaxInst,
	LdaName:   LdaInst,
	LdxName:   LdxInst,
	LdyName:   LdyInst,
	LsrName:   LsrInst,
	LxaName:   LxaInst,
	NopName:   NopInst,
	OraName:   OraInst,
	PhaName:   PhaInst,
	PhpName:   PhpInst,
	PhxName:   PhxInst,
	PhyName:   PhyInst,
	PlaName:   PlaInst,
	PlpName:   PlpInst,
	PlxName:   PlxInst,
	PlyName:   PlyInst,
	RlaName:   RlaInst,
	RolName:   RolInst,
	RorName:   RorInst,
	RraName:   RraInst,
	RtiName:   RtiInst,
	RtsName:   RtsInst,
	SaxName:   SaxInst,
	SbcName:   SbcInst,
	SecName:   SecInst,
	SedName:   SedInst,
	SeiName:   SeiInst,
	ShaName:   ShaInst,
	ShxName:   ShxInst,
	ShyName:   ShyInst,
	SloName:   SloInst,
	SreName:   SreInst,
	StaName:   StaInst,
	StxName:   StxInst,
	StyName:   StyInst,
	StzName:   StzInst,
	TasName:   TasInst,
	TaxName:   TaxInst,
	TayName:   TayInst,
	TrbName:   TrbInst,
	TsbName:   TsbInst,
	TsxName:   TsxInst,
	TxaName:   TxaInst,
	TxsName:   TxsInst,
	TyaName:   TyaInst,
	Bbr0.Name: Bbr0,
	Bbr1.Name: Bbr1,
	Bbr2.Name: Bbr2,
	Bbr3.Name: Bbr3,
	Bbr4.Name: Bbr4,
	Bbr5.Name: Bbr5,
	Bbr6.Name: Bbr6,
	Bbr7.Name: Bbr7,
	Bbs0.Name: Bbs0,
	Bbs1.Name: Bbs1,
	Bbs2.Name: Bbs2,
	Bbs3.Name: Bbs3,
	Bbs4.Name: Bbs4,
	Bbs5.Name: Bbs5,
	Bbs6.Name: Bbs6,
	Bbs7.Name: Bbs7,
	Rmb0.Name: Rmb0,
	Rmb1.Name: Rmb1,
	Rmb2.Name: Rmb2,
	Rmb3.Name: Rmb3,
	Rmb4.Name: Rmb4,
	Rmb5.Name: Rmb5,
	Rmb6.Name: Rmb6,
	Rmb7.Name: Rmb7,
	Smb0.Name: Smb0,
	Smb1.Name: Smb1,
	Smb2.Name: Smb2,
	Smb3.Name: Smb3,
	Smb4.Name: Smb4,
	Smb5.Name: Smb5,
	Smb6.Name: Smb6,
	Smb7.Name: Smb7,
}

// InstructionsByID maps OpcodeID to an instruction for constant-time lookup.
// Index 0 (InvalidOpcodeID) is nil.
var InstructionsByID = [OpcodeIDMax + 1]*Instruction{
	Adc:    AdcInst,
	Alr:    AlrInst,
	Anc:    AncInst,
	And:    AndInst,
	Ane:    AneInst,
	Arr:    ArrInst,
	Asl:    AslInst,
	Axs:    AxsInst,
	Bbr0ID: Bbr0,
	Bbr1ID: Bbr1,
	Bbr2ID: Bbr2,
	Bbr3ID: Bbr3,
	Bbr4ID: Bbr4,
	Bbr5ID: Bbr5,
	Bbr6ID: Bbr6,
	Bbr7ID: Bbr7,
	Bcc:    BccInst,
	Bcs:    BcsInst,
	Beq:    BeqInst,
	Bit:    BitInst,
	Bmi:    BmiInst,
	Bne:    BneInst,
	Bpl:    BplInst,
	Bra:    BraInst,
	Brk:    BrkInst,
	Bbs0ID: Bbs0,
	Bbs1ID: Bbs1,
	Bbs2ID: Bbs2,
	Bbs3ID: Bbs3,
	Bbs4ID: Bbs4,
	Bbs5ID: Bbs5,
	Bbs6ID: Bbs6,
	Bbs7ID: Bbs7,
	Bvc:    BvcInst,
	Bvs:    BvsInst,
	Clc:    ClcInst,
	Cld:    CldInst,
	Cli:    CliInst,
	Clv:    ClvInst,
	Cmp:    CmpInst,
	Cpx:    CpxInst,
	Cpy:    CpyInst,
	Dcp:    DcpInst,
	Dec:    DecInst,
	Dex:    DexInst,
	Dey:    DeyInst,
	Eor:    EorInst,
	Inc:    IncInst,
	Inx:    InxInst,
	Iny:    InyInst,
	Isc:    IscInst,
	Jmp:    JmpInst,
	Jsr:    JsrInst,
	Kil:    KilInst,
	Las:    LasInst,
	Lax:    LaxInst,
	Lda:    LdaInst,
	Ldx:    LdxInst,
	Ldy:    LdyInst,
	Lsr:    LsrInst,
	Lxa:    LxaInst,
	Nop:    NopInst,
	Ora:    OraInst,
	Pha:    PhaInst,
	Php:    PhpInst,
	Phx:    PhxInst,
	Phy:    PhyInst,
	Pla:    PlaInst,
	Plp:    PlpInst,
	Plx:    PlxInst,
	Ply:    PlyInst,
	Rla:    RlaInst,
	Rmb0ID: Rmb0,
	Rmb1ID: Rmb1,
	Rmb2ID: Rmb2,
	Rmb3ID: Rmb3,
	Rmb4ID: Rmb4,
	Rmb5ID: Rmb5,
	Rmb6ID: Rmb6,
	Rmb7ID: Rmb7,
	Rol:    RolInst,
	Ror:    RorInst,
	Rra:    RraInst,
	Rti:    RtiInst,
	Rts:    RtsInst,
	Sax:    SaxInst,
	Sbc:    SbcInst,
	Sec:    SecInst,
	Sed:    SedInst,
	Sei:    SeiInst,
	Sha:    ShaInst,
	Shx:    ShxInst,
	Shy:    ShyInst,
	Slo:    SloInst,
	Smb0ID: Smb0,
	Smb1ID: Smb1,
	Smb2ID: Smb2,
	Smb3ID: Smb3,
	Smb4ID: Smb4,
	Smb5ID: Smb5,
	Smb6ID: Smb6,
	Smb7ID: Smb7,
	Sre:    SreInst,
	Sta:    StaInst,
	Stx:    StxInst,
	Sty:    StyInst,
	Stz:    StzInst,
	Tas:    TasInst,
	Tax:    TaxInst,
	Tay:    TayInst,
	Trb:    TrbInst,
	Tsb:    TsbInst,
	Tsx:    TsxInst,
	Txa:    TxaInst,
	Txs:    TxsInst,
	Tya:    TyaInst,
}

// InstructionsForVariant returns the mnemonic registry exposed by one CPU
// variant. The returned map is independent, while its instruction definitions
// are the canonical immutable entries referenced by that variant's opcode table.
// An unsupported variant returns nil.
func InstructionsForVariant(variant CPUVariant) map[string]*Instruction {
	var table *[256]Opcode
	switch variant {
	case VariantNMOS6502, VariantNES6502, Variant6507, Variant6510:
		table = &Opcodes
	case Variant65C02:
		table = &Opcodes65C02
	case VariantSynertek65C02:
		table = &OpcodesSynertek65C02
	default:
		return nil
	}

	instructions := make(map[string]*Instruction)
	for _, opcode := range table {
		if opcode.Instruction == nil {
			continue
		}
		current, exists := instructions[opcode.Instruction.Name]
		if !exists || current.Unofficial && !opcode.Instruction.Unofficial {
			instructions[opcode.Instruction.Name] = opcode.Instruction
		}
	}
	return instructions
}
