package cpu6502

// Instruction name constants for easy access by external packages.
const (
	AdcName = "adc"
	AlrName = "alr" // Unofficial
	AncName = "anc" // Unofficial
	AndName = "and"
	AneName = "ane" // Unofficial - highly unstable (0x8B)
	ArrName = "arr" // Unofficial
	AslName = "asl"
	AxsName = "axs" // Unofficial
	BccName = "bcc"
	BcsName = "bcs"
	BeqName = "beq"
	BitName = "bit"
	BmiName = "bmi"
	BneName = "bne"
	BplName = "bpl"
	BrkName = "brk"
	BvcName = "bvc"
	BvsName = "bvs"
	ClcName = "clc"
	CldName = "cld"
	CliName = "cli"
	ClvName = "clv"
	CmpName = "cmp"
	CpxName = "cpx"
	CpyName = "cpy"
	DcpName = "dcp" // Unofficial
	DecName = "dec"
	DexName = "dex"
	DeyName = "dey"
	EorName = "eor"
	IncName = "inc"
	InxName = "inx"
	InyName = "iny"
	IscName = "isc" // Unofficial
	JmpName = "jmp"
	JsrName = "jsr"
	KilName = "kil" // Unofficial - halts the CPU (0x02, 0x12, 0x22, 0x32, 0x42, 0x52, 0x62, 0x72, 0x92, 0xB2, 0xD2, 0xF2)
	LasName = "las" // Unofficial
	LaxName = "lax" // Unofficial
	LdaName = "lda"
	LdxName = "ldx"
	LdyName = "ldy"
	LsrName = "lsr"
	LxaName = "lxa" // Unofficial - highly unstable (0xAB)
	NopName = "nop"
	OraName = "ora"
	PhaName = "pha"
	PhpName = "php"
	PlaName = "pla"
	PlpName = "plp"
	RlaName = "rla" // Unofficial
	RolName = "rol"
	RorName = "ror"
	RraName = "rra" // Unofficial
	RtiName = "rti"
	RtsName = "rts"
	SaxName = "sax" // Unofficial
	SbcName = "sbc"
	SecName = "sec"
	SedName = "sed"
	SeiName = "sei"
	ShaName = "sha" // Unofficial - unstable (0x93, 0x9F)
	ShxName = "shx" // Unofficial - unstable (0x9E)
	ShyName = "shy" // Unofficial - unstable (0x9C)
	SloName = "slo" // Unofficial
	SreName = "sre" // Unofficial
	StaName = "sta"
	StxName = "stx"
	StyName = "sty"
	TasName = "tas" // Unofficial - unstable (0x9B)
	TaxName = "tax"
	TayName = "tay"
	TsxName = "tsx"
	TxaName = "txa"
	TxsName = "txs"
	TyaName = "tya"
)
